global:
  slack_api_url: 'https://hooks.slack.com/services/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'

route:
  receiver: 'slack-notifications'
  group_by: ['alertname', 'instance']
  group_wait: 30s
  group_interval: 2m
  repeat_interval: 5m
  routes:
    - receiver: 'slack-danger'
      matchers:
        - alertname = "InstanceDown"

receivers:
- name: 'slack-danger'
  slack_configs:
  - channel: '#alerts'
    send_resolved: true
    title: "!!!! {{ .CommonAnnotations.summary }} !!!!"
    text: "DANGER : {{ .CommonAnnotations.description }}"
- name: 'slack-notifications'
  slack_configs:
  - channel: '#alerts'
    send_resolved: true
    title: "{{ .CommonAnnotations.summary }}"
    text: "{{ .CommonAnnotations.description }}"

inhibit_rules:
- source_matchers:
    - severity="critical"
  target_matchers:
    - severity="warning"